### ISSUE TITLE
Add "אז מה עכשיו" section

### ISSUE THREAD

**Issue by RoyTennenbaum** [Maakaf/maakaf-website#10]
### Description

make sure to follow the figma design.

Relevant files:
- components/Home/WhatNow.tsx
- app/page.tsx

### Additional information

If/when creating sub components is necessary, create a new folder called "WhatNow" and insert the WhatNow.tsx in there, together with all related sub components.

**Comment by hagarfisher** [comment]
I'd like to take this issue :)

**Comment by RoyTennenbaum** [comment]
Good luck Hagar :)

**Comment by RoyTennenbaum** [comment]
How is it going? ask in our community discord channel if you encounter any issues or need to clarify something 😃
