### ISSUE TITLE
Fix font-family in top navbar, footer, projects

### ISSUE THREAD

**Issue by adirkandel** [Maakaf/maakaf-website#105]
## Top navbar
![Image](https://github.com/Maakaf/maakaf-website/assets/12512909/92bed9b8-06cc-4954-99d6-aa8404198866)

## Footer
![Image](https://github.com/Maakaf/maakaf-website/assets/12512909/56737a8a-51e1-428c-ae9d-f0ad801d1e3a)

## Projects page
![Image](https://github.com/Maakaf/maakaf-website/assets/12512909/6ec880fa-9f92-45d6-961d-ced1d07e6358)

![Image](https://github.com/Maakaf/maakaf-website/assets/12512909/5e5990a3-9d72-4e44-b594-7c462afef8dc)

**Comment by RoyTennenbaum** [comment]
@adirkandel where aare these screenshots coming from? 
From a quick overview of the website all fonts seem ok, maybe they revert to the fallback font on certain devices?

**Comment by Darkmift** [comment]
@adirkandel whats the status here please?

**Comment by Darkmift** [comment]
Upon inspection is fixed.
