### ISSUE TITLE
Fix the filters settings background on dark mode

### ISSUE THREAD

**Issue by adirkandel** [Maakaf/maakaf-website#106]
### Website
![Image](https://github.com/Maakaf/maakaf-website/assets/12512909/9d630496-ab91-49ae-a55d-c8e1fe99bc61)

### Figma
![Image](https://github.com/Maakaf/maakaf-website/assets/12512909/38483a45-5626-4273-b701-64714f0fb50a)

**Comment by noams24** [comment]
@adirkandel Done.
