### ISSUE TITLE
Newbies - Hero section

### ISSUE THREAD

**Issue by adirkandel** [Maakaf/maakaf-website#107]
link to [Figma](https://www.figma.com/file/Ib05mHSvinzf9NNqIqftLR/Maakaf?type=design&node-id=2493%3A4761&mode=design&t=68Y0tmyYUcpDPR0p-1)

![Image](https://github.com/Maakaf/maakaf-website/assets/12512909/0152097c-cc82-4b86-8389-fd52a4bce8c5)

![Image](https://github.com/Maakaf/maakaf-website/assets/12512909/d87a55da-9efc-41e2-8c6f-23622be8a8fa)

**Comment by OshriAsulin** [comment]
Hey @adirkandel  I opened a PR #116 that suggests this issue

**Comment by adirkandel** [comment]
Thank you buddy, i'll try to review it ASAP

**Comment by Darkmift** [comment]
Closed as completed by @OshriAsulin
