### ISSUE TITLE
Newbies - Terms section

### ISSUE THREAD

**Issue by adirkandel** [Maakaf/maakaf-website#108]
Link to [Figma](https://www.figma.com/file/Ib05mHSvinzf9NNqIqftLR/Maakaf?type=design&node-id=2493%3A4761&mode=design&t=68Y0tmyYUcpDPR0p-1)

![Image](https://user-images.githubusercontent.com/12512909/268110494-8dbc8a7e-82ac-4b84-a95e-c8e6e34f934a.png)

![Image](https://user-images.githubusercontent.com/12512909/268110274-c9eee93a-1022-489e-91e8-106339bb92d2.png)

**Comment by rotembarsela** [comment]
Please assign me @adirkandel

**Comment by adirkandel** [comment]
@rotembarsela you're the man, thanks!
