### ISSUE TITLE
Newbies - Steps section

### ISSUE THREAD

**Issue by adirkandel** [Maakaf/maakaf-website#109]
Link to [figma](https://www.figma.com/file/Ib05mHSvinzf9NNqIqftLR/Maakaf?type=design&node-id=2493%3A4761&mode=design&t=68Y0tmyYUcpDPR0p-1)

![Image](https://user-images.githubusercontent.com/12512909/268110671-3cef3aae-71a2-46da-a3c2-5383cc454dc8.png)

![Image](https://user-images.githubusercontent.com/12512909/268110773-19fdf618-ccb1-4258-882d-ea51d3ce5e32.png)

**Comment by noams24** [comment]
@adirkandel Can you assign me?

**Comment by noams24** [comment]
I think you can close this issue

**Comment by Drorka** [comment]
please assign me

**Comment by noams24** [comment]
@Drorka Isn't it finished? https://maakaf-website.vercel.app/maintainers

**Comment by Drorka** [comment]
> @Drorka Isn't it finished? https://maakaf-website.vercel.app/maintainers

you're referring to the maintainers steps, the content is not the same as the newbies steps

**Comment by Drorka** [comment]
I would refactor it to be a common component that will get the steps content in it's props. 
then i'd use it both in maintainers and newbies

**Comment by adirkandel** [comment]
@Drorka It's yours, thank you!
You're on FIRE!!! 🔥💪

**Comment by Darkmift** [comment]
Closing as completed by @Drorka
