### ISSUE TITLE
Add the Footer

### ISSUE THREAD

**Issue by RoyTennenbaum** [Maakaf/maakaf-website#11]
### Description

make sure to follow the figma design.
grab the icons from there as well.

Relevant files:
- components/Footer/Footer.tsx
- app/layout.tsx

**Comment by TomRytt** [comment]
היי, אשמח לקחת את ה-Footer

**Comment by RoyTennenbaum** [comment]
Unable to contact @xarielah for over a week, unfortunately relinquishing this assignment.
Ask here to be assigned.

**Comment by rotembarsela** [comment]
@TomRytt

**Comment by TomRytt** [comment]
> @TomRytt 

I'd be happy to take this issue

**Comment by TomRytt** [comment]
> @rotembarsela 

I'd be happy to take this issue

**Comment by rotembarsela** [comment]
> > @rotembarsela
> 
> I'd be happy to take this issue

@RoyTennenbaum
