### ISSUE TITLE
Newbies - Where everything happens

### ISSUE THREAD

**Issue by adirkandel** [Maakaf/maakaf-website#110]
Link to [Figma](https://www.figma.com/file/Ib05mHSvinzf9NNqIqftLR/Maakaf?type=design&node-id=2493%3A4761&mode=design&t=68Y0tmyYUcpDPR0p-1)

![Image](https://user-images.githubusercontent.com/12512909/268110966-1b51175e-d6a7-4f97-86d0-5f2678c6ff4c.png)

![Image](https://user-images.githubusercontent.com/12512909/268110868-7c04e9ab-2bbb-46c3-bdc6-ece57597255c.png)

**Comment by Drorka** [comment]
please assign me

**Comment by adirkandel** [comment]
@Drorka You got it, 10x 🙏
