### ISSUE TITLE
Website Section Title - Generic Component

### ISSUE THREAD

**Issue by rotembarsela** [Maakaf/maakaf-website#118]
### Description

* Every section has the same title, there is no a generic component that implemented on every section
* Creating a generic component which will be used across the site

### Screenshots

![image](https://github.com/Maakaf/maakaf-website/assets/44998514/18625e9c-a1c6-45d5-add2-789a32d82700)

**Comment by rotembarsela** [comment]
I'll fix that on my next PR

**Comment by Drorka** [comment]
i already created a common component for this, it's implemented in the maintainers and newbies pages.
so we can use it in the homepage as well

**Comment by adirkandel** [comment]
@rotembarsela I agree with @Drorka she did it already
