### ISSUE TITLE
Footer - Background Color + Icons default color and navigation links

### ISSUE THREAD

**Issue by rotembarsela** [Maakaf/maakaf-website#135]
### Description

* Small fix: change the background color and the icons default color so it will match the figma
(tip: change the stroke color on the svgs)

* Make the links work and navigate to the correct pages

### Screenshots

Current:
![image](https://github.com/Maakaf/maakaf-website/assets/44998514/17b8db4d-1e48-498e-a175-55eb2843c5e8)

Figma:
![image](https://github.com/Maakaf/maakaf-website/assets/44998514/d541b6d1-0e2d-48ef-a73a-153db6a98aa5)

**Comment by amabelleS** [comment]
Hey:) I would love to take this issue. 
Do I need a link to the project on Figma or should I use a color picker for the screenshots for now?

**Comment by Darkmift** [comment]
@amabelleS apologies for the tardy reply.
Figma for project is currently not available I am working to resolve the issue with the Designer Efi Gelfi
