### ISSUE TITLE
Add support for i18n to website

### ISSUE THREAD

**Issue by iemafzalhassan** [Maakaf/maakaf-website#138]
### Description

**Issue Description:**

**Problem**

The website currently lacks a language switcher, hindering users who prefer to browse in languages other than the default. To enhance the user experience and accommodate a diverse audience, we propose the addition of a language switcher.

**Solution**

Implementing a language switcher will empower users to select their preferred language, enabling them to navigate the website and access content in a language they are most comfortable with.

**Key Features Requested**

- Button: A user-friendly interface for selecting languages.
- Dynamic Content: seamless transition between languages with dynamic content updates.
- Accessibility: Ensure the language switcher is easily accessible, possibly in the header, footer, or navigation menu.

### Screenshots

![Screenshot from 2023-12-14 13-39-21](https://github.com/Maakaf/maakaf-website/assets/136967348/c08fb8a4-91a6-49a6-950c-4507a715369d)

### Additional information

URL: [website link here](https://maakaf-website.vercel.app/)

**Comment by Darkmift** [comment]
I agree @iemafzalhassan 
Refactoring this project to i18n will open many options.
Would you like to work on that?

**Comment by Darkmift** [comment]
I closed #67 lets focus work on i18n to this issue.

**Comment by Darkmift** [comment]
@noams24 

Hey this is a great step in the right direction!
I want you to review this:
https://github.com/hasadna/open-bus-map-search/blob/main/src/locale/allTranslations.ts

The i18n implementation should allow us to effortlessly change languages and have TS support.

**Comment by noams24** [comment]
> @noams24
> 
> Hey this is a great step in the right direction! I want you to review this: https://github.com/hasadna/open-bus-map-search/blob/main/src/locale/allTranslations.ts
> 
> The i18n implementation should allow us to effortlessly change languages and have TS support.

So how do you want me to contribute to this issue?

**Comment by Darkmift** [comment]
Review what I sent you and implement it in our project.

**Comment by noams24** [comment]
@Darkmift Is there a Figma design to the change language option?

**Comment by Darkmift** [comment]
No.
I am not sure there will be one in the works either
first lets focus on text changes then worry about RTL and visual changes
later.
