### ISSUE TITLE
Clarification required re Component

### ISSUE THREAD

**Issue by Darkmift** [Maakaf/maakaf-website#142]
### What would you like to share?

- see components/common/button
- As far as I can tell this should be deprecated or documented why its needed.

**Comment by anaalamed** [comment]
components/common/button is currently used only on MaintainerForm on MaintainersPage 
<img width="1125" alt="image" src="https://github.com/Maakaf/maakaf-website/assets/75525964/93af909b-e955-454c-b4d9-3f0cdfc0df5c">

So, we can move it to the maintainers section or try to reuse this class to be common among all the buttons on the website. 

Do you prefer just moving it?
Can you assign it to me?

**Comment by Tamir198** [comment]
I am working on this page right now, I will remove this button as it contains nothing special to be considered different componenet
