### ISSUE TITLE
feature: Terms of use and Privacy settings are rquired

### ISSUE THREAD

**Issue by Darkmift** [Maakaf/maakaf-website#143]
### Description

- Design links in footer call for:
1. Privacy settings
2. Terrms of use

### Screenshots

![image](https://github.com/Maakaf/maakaf-website/assets/12433441/5b9978b3-95c5-4e8a-927f-f56f94219ef8)

**Comment by DafnaPundak** [comment]
Sure
I will be happy to ask a few things before, I hope its ok to ask here.
Where should I take the content of those pages?
ALso, is the Figma link provided in the README not working only for me?

**Comment by Darkmift** [comment]
> Where should I take the content of those pages?

I recommend looking up generic ones online and adapting to the site as needed.

> Also, is the Figma link provided in the README not working only for me?

Figma is view by invite only,DM on discord I will invite you to figma.

**Comment by DafnaPundak** [comment]
@Darkmift 
ETA - I hope to finish this task by the end of next week

**Comment by DafnaPundak** [comment]
@Darkmift 
Hey, a small update
I finished creating the new pages and writing the content. I just want to add a button to Discord
