### ISSUE TITLE
Proejcts filters are not working

### ISSUE THREAD

**Issue by Tamir198** [Maakaf/maakaf-website#149]
### Description

I cant change the projects filters the buttons are not working

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/17141710-8f09-4653-9c96-9a316bae8328)

Also press the x button here: 

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/bff5c30a-ec63-4faa-b02e-09e490e5c550)

Is not doing anything

**Comment by Darkmift** [comment]
Hey @Tamir198 please see #104
