### ISSUE TITLE
Footer is too large on mobile

### ISSUE THREAD

**Issue by Tamir198** [Maakaf/maakaf-website#150]
### Description

The footer is taking a lot of space in the mobile version : 

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/76d30121-952a-4fe3-820f-755859c5ae67)

**Comment by RoyTennenbaum** [comment]
@Tamir198 would you like to take care of this? :)

**Comment by Tamir198** [comment]
Sure thing
