### ISSUE TITLE
"Our paths" section links are broken

### ISSUE THREAD

**Issue by Tamir198** [Maakaf/maakaf-website#151]
### Description

Right now pressing anay of those buttons will link you back to the main page :

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/dab1d99d-ed92-499d-b4da-740bd12da8b3)

Would be nice if the discord button would work for exmaple since the community is active on discord

**Comment by Tamir198** [comment]
Thank you for mentioning the duplications

**Comment by Darkmift** [comment]
@Tamir198 If you can I would love a review of the PR I submittede to address the issue.

**Comment by Tamir198** [comment]
Sure, i will aee to it later tosay. Link to the pr?

**Comment by Darkmift** [comment]
> Sure, i will see to it later today. Link to the pr?
#144
