### ISSUE TITLE
fix: Eslint and prettier setup

### ISSUE THREAD

**Issue by Darkmift** [Maakaf/maakaf-website#156]
### What would you like to share?

- Eslint and prettier config require some additional configuration to ensure proper enforcement

**Comment by RoyTennenbaum** [comment]
This was a large issue some time ago, we attempted to solve it and eventually implemented husky in the project with minor configs. It's not perfect since we didn't exactly cover 100% of the edge cases...

If someone can look into it it will be appreciated :D

**Comment by ronnahmias** [comment]
> ### What would you like to share?
> * Eslint and prettier config require some additional configuration to ensure proper enforcement


which config do you want to enforce?
@Darkmift

**Comment by Darkmift** [comment]
> > ### What would you like to share?
> > 
> > * Eslint and prettier config require some additional configuration to ensure proper enforcement
> 
> which config do you want to enforce? @Darkmift

TS, lint and prettier mainly.
ensure they are ran by husky to prevent commits with TS/lint issues

**Comment by ronnahmias** [comment]
There is husky that do lint check what is missing?

**Comment by Darkmift** [comment]
Current configs are now stable
