### ISSUE TITLE
להוסיף קישורים בפוטר

### ISSUE THREAD

**Issue by UrielOfir** [Maakaf/maakaf-website#159]
### Description

להוסיף קישור לדף של הקהילה באפליקציית מיטאפ-
https://www.meetup.com/maakaf/

קישור ליוטיוב של מעקף-
https://www.youtube.com/@maakaf-os

**Comment by anaalamed** [comment]
can I take it?

**Comment by Darkmift** [comment]
> can I take it?

Sure thing!
