### ISSUE TITLE
Website breaks on mobile

### ISSUE THREAD

**Issue by Tamir198** [Maakaf/maakaf-website#165]
### Description

On mobile, the website looks like this : 

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/03878135-6327-4f0e-83d0-ac5b368cc47a)

Notice the blank space to the right? 

I think that on mobile there is an element that should be hidden (the "space" element is selected i the devtools in this picture) : 

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/d2f2caa7-24b3-447a-975b-801dbce139f0)

**Comment by ronnahmias** [comment]
> ### Description
> On mobile, the website looks like this :

The issue is is only on width 350px and lower.

**Comment by Darkmift** [comment]
Who wants to fix this?

**Comment by Darkmift** [comment]
Upon closer inspection the issue occurs below the supported minimal width per figma specs. (395px)
At this point I see no reason to address this issue.
