### ISSUE TITLE
Wrong language when opening up the page

### ISSUE THREAD

**Issue by Tamir198** [Maakaf/maakaf-website#169]
### Description

As you can see in the image the website link is `http://localhost:3000/en` and also the language select in set to `ENGLISH` but the website is in hebrew by default

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/7ee0728d-8969-435b-9386-98b8c59dca7a)

This is happening only in development mode, and this is because if this part of the code: 

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/c0679674-9160-4a6a-8da7-b192bb0fb7cd)

**Comment by Darkmift** [comment]
The website is not yet updated with english.

You can notice,for now, the title does change.

We need a lot of work to refactor the content.

**Comment by Tamir198** [comment]
OK good to know this, thanks
