### ISSUE TITLE
Improve single project card

### ISSUE THREAD

**Issue by Tamir198** [Maakaf/maakaf-website#170]
### Description

Right now under the projects page, a single project looks like this : 

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/fd38f80e-58e0-4a35-afc8-93c6e8c3e08c)

It is missing a couple of things, like GitHub link + update on the amount of contributors the project has etc.. : 

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/2049d245-6449-4a6b-9eb9-5808db136546)

**Comment by Tamir198** [comment]
I would like to work on this

**Comment by Darkmift** [comment]
> I would like to work on this

Great,this really could use some work!
