### ISSUE TITLE
feature: Filter feature phase 2

### ISSUE THREAD

**Issue by Darkmift** [Maakaf/maakaf-website#179]
### Description

- enable first filter row
- refactor filter logic by redesgining the backend fetch logic
  I want to split to a cron that gets fresh data periodically and stores to a db that will serve the clients with sort/filtered requests for better performance ,scalability and ensuring minimal use of Github GQL calls (currently limited to 5K requests per hour).

**Comment by rotembarsela** [comment]
If this issue has not been addressed, please assign it to me

**Comment by Darkmift** [comment]
Closing this and continuing discussion in #215
