### ISSUE TITLE
feature: Create memeber page template

### ISSUE THREAD

**Issue by Tamir198** [Maakaf/maakaf-website#183]
### Description

We need to create a template for this page  (we can use dummy data for now and get really data later on): 

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/61f11604-f994-4c67-9322-9f2a6d82c822)

**Comment by Tamir198** [comment]
I will work on this

**Comment by ronnahmias** [comment]
How I can see the page? There is need to be link in the header?

**Comment by Tamir198** [comment]
In here : 

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/7c2b4607-bf69-41d9-9f49-dc74c74269be)


@ronnahmias
