### ISSUE TITLE
feature: projects page - add link to newbies

### ISSUE THREAD

**Issue by ronnahmias** [Maakaf/maakaf-website#185]
### Description

Add Link with hover underline to איך מתחילים לכתוב קוד פתוח?
The link will go to : /newbies

### Screenshots

![image](https://github.com/Maakaf/maakaf-website/assets/52237617/1adb7582-8cac-4063-bce7-dcb3174e376d)

**Comment by ronnahmias** [comment]
@Darkmift 
Can assign me please?

**Comment by Darkmift** [comment]
> @Darkmift Can assign me please?

Done!
