### ISSUE TITLE
Fix: Project page grid

### ISSUE THREAD

**Issue by ronnahmias** [Maakaf/maakaf-website#186]
### Description

The project page is currently set to width 100%, but according to the Figma design, there should be some spacing (air) on the sides. This discrepancy affects both desktop and mobile designs and requires adjustments to ensure alignment with the design specifications.

### Screenshots

Website:
![image](https://github.com/Maakaf/maakaf-website/assets/52237617/3a85a966-42c4-44d1-b08d-69c6fe04be08)
![image](https://github.com/Maakaf/maakaf-website/assets/52237617/97f9904e-820f-4615-8d4f-071de38903a5)

Figma:
![image](https://github.com/Maakaf/maakaf-website/assets/52237617/0e1a4d25-44d4-4d28-b00b-37b3388c8357)
![image](https://github.com/Maakaf/maakaf-website/assets/52237617/729b3c8e-a41d-41ab-a479-f78be19bd40b)

**Comment by Darkmift** [comment]
Would you like to work on this issue?

**Comment by ronnahmias** [comment]
Yes @Darkmift

**Comment by Darkmift** [comment]
All yours 😃
