### ISSUE TITLE
The favicon is not being displayed

### ISSUE THREAD

**Issue by anaalamed** [Maakaf/maakaf-website#189]
### Description

The favicon is not being displayed 

### Screenshots

<img width="444" alt="image" src="https://github.com/Maakaf/maakaf-website/assets/75525964/e0a2d337-69c5-4be6-93be-94970d12d2cd">

**Comment by Tamir198** [comment]
Seems fine on my pc: 

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/20dca308-3cec-4745-b2ba-2323f1b5139d)

Browsing Chrome 122

**Comment by Darkmift** [comment]
> ### Description
> The favicon is not being displayed
> 
> ### Screenshots
> <img alt="image" width="444" src="https://private-user-images.githubusercontent.com/75525964/313341858-e0a2d337-69c5-4be6-93be-94970d12d2cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MjM2MDUsIm5iZiI6MTcxMDYyMzMwNSwicGF0aCI6Ii83NTUyNTk2NC8zMTMzNDE4NTgtZTBhMmQzMzctNjljNS00YmU2LTkzYmUtOTQ5NzBkMTJkMmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDIxMDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0OGMwMzNkNWZhZmQxYWU0NWQ1MDY0MzgxMDM5MjVlZDE1ZmE4N2E4NDRhYzU0ZTEyNzhlYjU4NWZkZWQzOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k0htujHENQmTx_648Gi5yLnI2RhOTzIPPYmumjd9VSc">
> ### Additional information
> _No response_

I suspect a cache issue.
I can confirm on my end the icon is displayed.
