### ISSUE TITLE
Run prettier on pr

### ISSUE THREAD

**Issue by Tamir198** [Maakaf/maakaf-website#197]
### Description

It could be nice to run prettier on every pr. 
That way the project will look the same no matter who pushed it.

**Comment by ronnahmias** [comment]
Each commit, there's a husky config that does it

**Comment by Tamir198** [comment]
@ronnahmias 
I don't think it's working tho because when I opened pr (the code was merged from the latest main code) I had over 20 files affected by the prettier formating command in the package json (I didn't change anything before running it)

**Comment by ronnahmias** [comment]
I see that there is workflow for checking it
https://github.com/Maakaf/maakaf-website/actions/workflows/pr-checks.yml

**Comment by Tamir198** [comment]
Would be nice if the workflow would just run this formatting command instead of checking it ( I mean if the code needs formating its better to auto format than to block pr because of this )

**Comment by Darkmift** [comment]
see #210 
I merged and tweaked husky

**Comment by Darkmift** [comment]
![image](https://github.com/Maakaf/maakaf-website/assets/12433441/350f56dd-78de-4dff-9337-94c3c5b27cf0)

I tweaked husky to ruhn lint and prettier on commit.
you will see its logs only if you ommit from the terminal not if you commit via the UI

confirm this and close issue if its behaviour is same for you aswell
@Tamir198

**Comment by Tamir198** [comment]
Yes, I see it working as well : 

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/bd65c048-d815-4916-a020-8633dfb0b1f1)
