### ISSUE TITLE
Memeber search ui change

### ISSUE THREAD

**Issue by Tamir198** [Maakaf/maakaf-website#201]
### Description

This search input in members page : 

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/e9e1dda2-b7f8-44c8-8eae-8cf1d3632214)

Should look like this : 

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/5fa4adc3-b70a-4fd3-b832-a1e9638b70bf)

**Comment by Tamir198** [comment]
I will work on this

**Comment by develad** [comment]
Hey @Tamir198 
Please review #203 before you couniting pushing more pull requests. I've done a few changes

**Comment by Tamir198** [comment]
Cool, as long as you will open an issue before submitting a PR it will be fine and no conflicts should be found

**Comment by develad** [comment]
@Tamir198 
Noted
