### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by zushar** [Maakaf/maakaf-website#205]
### Description

Translate בואו לדסקורד in about page

**Comment by zushar** [comment]
I would be happy to take this and if it goes good I will keep doing translation.

**Comment by Darkmift** [comment]
- note that translation hook is now available in client components as well.

**Comment by OliaKr** [comment]
I can help with translation of questions and answers in the Faqs component.

**Comment by Darkmift** [comment]
> I can help with translation of questions and answers in the Faqs component.

great!
Assigning you to this issue

**Comment by DvirMon** [comment]
I am ready to help. Which page can I do?

**Comment by zushar** [comment]
i missed the opportunity i see Everything has already  been translated
