### ISSUE TITLE
Select specific technology in projects page

### ISSUE THREAD

**Issue by UrielOfir** [Maakaf/maakaf-website#209]
### Description

Regarding the projects page,
To make it easier for users, it should be easy to choose one technology they are looking for.
Right now all other technologies have to be canceled and it's oppressive.

**Comment by Darkmift** [comment]
@EfiGelfi what would be a good UI application?

**Comment by Darkmift** [comment]
update on #215

**Comment by Darkmift** [comment]
Applied said logic in #219 
@UrielOfir verify please

**Comment by Darkmift** [comment]
verified
