### ISSUE TITLE
Styling went bad

### ISSUE THREAD

**Issue by develad** [Maakaf/maakaf-website#212]
### Description

The styling in the members page went off in the current version. In #203 it was good

![Screenshot_20240322-142501_Chrome](https://github.com/Maakaf/maakaf-website/assets/70572668/671680a7-38ce-4b1b-9ae7-66d5855e0ddc)

**Comment by Darkmift** [comment]
@develad yes there was a lot of re work
Sorry @Tamir198 

If anyone wants to go over this and fix it please do.

**Comment by develad** [comment]
@Darkmift 

I volunteer to do this task. In the coming days there will be a style fix.
