### ISSUE TITLE
Language switch button on mobile view

### ISSUE THREAD

**Issue by develad** [Maakaf/maakaf-website#213]
### Description

In the current version there isn't an option to switch between languages while in desktop view there is.

A good solution is to implement this button on the mobile navigation bar or header

**Comment by OliaKr** [comment]
Hey, I can help with rendering the button in the mobile view.

@Darkmift Do you also mean that UI button improvements are needed?

**Comment by Darkmift** [comment]
> Hey, I can help with rendering the button in the mobile view.
> 
> @Darkmift Do you also mean that UI button improvements are needed?

Yup anyhting that can make this better is welcome

**Comment by EfiGelfi** [comment]
Iv'e added the button to the design on Figma now. It didn't exist because we didn't plan to have an English version.
Please use the same button on the mobile, inside the menu as presented on Figma. 
And let me know if there are any more issues with it. Thanks!

**Comment by Darkmift** [comment]
> Iv'e added the button to the design on Figma now. It didn't exist because we didn't plan to have an English version. Please use the same button on the mobile, inside the menu as presented on Figma. And let me know if there are any more issues with it. Thanks!

Amazing!!

**Comment by OliaKr** [comment]
Working on it!

**Comment by OliaKr** [comment]
So the button should be inside the drawer
![Capture8](https://github.com/Maakaf/maakaf-website/assets/118835746/f34429bc-e21c-4e6f-9251-034fff9d9c66)
. Do we need it outside near the burger menu as well?

**Comment by Darkmift** [comment]
> So the button should be inside the drawer ![Capture8](https://private-user-images.githubusercontent.com/118835746/318514552-f34429bc-e21c-4e6f-9251-034fff9d9c66.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzY1NDYsIm5iZiI6MTcxNTg3NjI0NiwicGF0aCI6Ii8xMTg4MzU3NDYvMzE4NTE0NTUyLWYzNDQyOWJjLWUyMWMtNGU2Zi05MjUxLTAzNGZmZjlkOWM2Ni5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxNjE3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjMyOGQ2OGFlOWJhZjRhMDBhMjQwYzVhYTZkY2Y5Mzk3NTVmM2VmNGNkM2IxNWIzZjhlMGI4OWUwNDVhMjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-3bPXCg6NE-FjYN1de3wW7zbYbj0-xcV0Q1phP9T_LI) . Do we need it outside near the burger menu as well?

Inside the drawer is good enough @OliaKr

**Comment by Darkmift** [comment]
closing and moving discussion to #271
