### ISSUE TITLE
Change add project form state managmant

### ISSUE THREAD

**Issue by Tamir198** [Maakaf/maakaf-website#214]
### Description

Rig: 
ht now, this form : 

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/2ed8d7b8-b896-4d20-b216-4a9ac0630747)

Is using a lot of `useState` and we need to refactor this to use the `useForm` hook

**Comment by Darkmift** [comment]
Lookup server actions for the remote request
(You can use inside the formsubmithandler.

**Comment by DvirMon** [comment]
in weach folder is it located?

**Comment by DvirMon** [comment]
Hi @Tamir198,

After reviewing the code, it seems that you're done apply the useForm hook. Is there something more that needs to be added?

**Comment by Tamir198** [comment]
I have a small fix that I will puah later on and open pr.
Will tag you if anything more is needed

**Comment by Tamir198** [comment]
@DvirMon Just opened my pr 
Need too add icon to the data sending bu submitting the form 
wanna go for it ?
