### ISSUE TITLE
Projects page is empty on first enter

### ISSUE THREAD

**Issue by TomRytt** [Maakaf/maakaf-website#215]
### Description

When first entering the projects page, it shows no projects (You can enter in incognito to replicate)

### Screenshots

![image](https://github.com/Maakaf/maakaf-website/assets/86921461/d52b5d0b-5331-4eb1-a780-42566ef1fba3)

### Additional information

I would like to be assigned to this issue  :)

**Comment by Darkmift** [comment]
good catch
 I am making an endpoint in :
 https://github.com/Maakaf/Baas-data-provider
 
 then rework that page to fetch from there.
 at present I rely on caching hacks and localstorage which causing some issues.
 
 this approach will get rid of those and a lot of addiitonal code/hooks.

**Comment by Darkmift** [comment]
![BAAS](https://github.com/Maakaf/maakaf-website/assets/12433441/b64b3634-cad8-4f6f-9c4e-f9e3061c0d65)

There's a new service and now we need to refactor that page to use it.

**Comment by Darkmift** [comment]
Fixed in #219 

@TomRytt please verify

**Comment by Darkmift** [comment]
Fixed in latest commits of #219
