### ISSUE TITLE
Filter Tag Not Removing After Re Click and Unexpected Behavior When Selecting Multiple Filters

### ISSUE THREAD

**Issue by DvirMon** [Maakaf/maakaf-website#220]
### Description

When testing the filter functionality of the projects I encountered two issues:

1. After selecting a filter tag, I expected that on a second click the filter be removed from the active filters. However, no action was observed.

2. Additionally, when selecting multiple filters sequentially, clicking on one of them again removes the other filters. This behavior is unexpected as I would anticipate only the filter that was clicked to be removed.

**Expected Behavior:**

1. Clicking on a filter tag should remove it from the active filters, updating the displayed content accordingly 

3. When selecting multiple filters, clicking on one of them should only remove that specific filter from the active filters, leaving the others unaffected.

**Steps to Reproduce:**

1. Navigate to the section with filterable content.
2. Select a filter tag to apply it.
3. Observe that clicking on the filter tag again does not remove it.
4. Select multiple filters sequentially.
5. Click on one of the selected filters.
6. Note that one of the selected filters is unexpectedly removed.

### Screenshots

![Screenshot from 2024-03-26 11-12-45](https://github.com/Maakaf/maakaf-website/assets/55688722/da50e7f7-2b4d-4a2b-b377-e2550993508e)

After reclick on javascript filter

![Screenshot from 2024-03-26 11-12-59](https://github.com/Maakaf/maakaf-website/assets/55688722/00828bc3-8975-45c4-9356-f65853a85219)

**Comment by DvirMon** [comment]
@Darkmift

**Comment by Darkmift** [comment]
fixed in #218
