### ISSUE TITLE
Tailwind config fix

### ISSUE THREAD

**Issue by rotembarsela** [Maakaf/maakaf-website#24]
configure the tailwind config file so it has all the figma colors,fonts,spacing,etc... (for light and dark mode as well)

that will help with auto complete tailwind classes and use the right patterns for the website
Relevant files:

tailwind.config.js

PR: #22 

![image](https://github.com/Maakaf/maakaf-website/assets/44998514/669848f8-be91-4723-8305-d1011c52ab30)

**Comment by rotembarsela** [comment]
i'll take that issue

**Comment by RoyTennenbaum** [comment]
#22 closed
