### ISSUE TITLE
Whats now button is not doing anything

### ISSUE THREAD

**Issue by Tamir198** [Maakaf/maakaf-website#241]
### Description

Clicking the button (main page at the bottom) currently is not doing any thing

### Screenshots

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/be295397-0787-4f6f-8887-321045b9d103)

**Comment by Tamir198** [comment]
When this button is pressed we need to scroll up to this part of the page (both in the main page : 

![image](https://github.com/Maakaf/maakaf-website/assets/34707669/c1259f92-dda9-415a-a95c-1437918f3619)

**Comment by OliaKr** [comment]
I'll be happy to help with that

**Comment by Darkmift** [comment]
> Done

Hey,
Please share your work via a PR?

**Comment by Darkmift** [comment]
ty @OliaKr 
looks like it was merged already
closing
