### ISSUE TITLE
Adding skeleton loading spinner in members page as described in Figma

### ISSUE THREAD

**Issue by develad** [Maakaf/maakaf-website#246]
### Description

Adding skeleton loading spinner in members page as described in Figma

![Untitled](https://github.com/Maakaf/maakaf-website/assets/70572668/28ebb0f9-f457-4c59-b2ed-77f00720e1df)

**Comment by develad** [comment]
I will be working on this feature! 💀

**Comment by Tamir198** [comment]
@develad  Hey, please notice that now the project is fetching really data and not the dummy members data.
So for now you will see one item (We have a lot of members so I think its ok to show the loader just like in the figma for now and later on it will fit when we add more data to it)

**Comment by develad** [comment]
> @develad Hey, please notice that now the project is fetching data from our BAAS repo, not the dummy data. So for now you will see one item (We have a lot of members so I think it`s ok to show the loader just like in the Figma for now and later on it will fit when we add more data to it)

Hi @Tamir198 🖐

I've created a custom SkeletonCards component the can receive by props the number of cards to render on the screen (by default its 6 skeleton cards if not specified otherwise) 

Check pull-request #250 for more info
