### ISSUE TITLE
Add generic list componenet

### ISSUE THREAD

**Issue by Tamir198** [Maakaf/maakaf-website#259]
### Description

In the project, we have a lot of `array.map(item => <component data={item}/>)`.

It would be nice to have a single generic list component. The component should receive a component to render and an array (the data) as props. 
Once done, we will need to refactor the places using the `array.map...` into the list component. 

This will save a lot of code duplication across the project.

**Comment by Darkmift** [comment]
its far too generic to offer added value....given classes/structure variances its best to stick to plain js iteration where needed.
