### ISSUE TITLE
Change English Font

### ISSUE THREAD

**Issue by noams24** [Maakaf/maakaf-website#269]
### What would you like to share?

The font "Birzia" only supports uppercase English letters.
The website should support lowercase letters too.

**Comment by Darkmift** [comment]
@EfiGelfi your toughts?

**Comment by EfiGelfi** [comment]
The font is just for certain headings. I don't see the problem. For text we have a different font that supports lower case.

**Comment by noams24** [comment]
@EfiGelfi 
![image](https://github.com/Maakaf/maakaf-website/assets/80849999/440bb4e5-4b22-4932-87a1-e95eb5808fd8)

So apply the header font to the rest of the text?

**Comment by EfiGelfi** [comment]
**Birzia** is for the headings and all uppercase. 
**Inter** is for text or sub heading if it helps, and it can be used with lowercase.

**Comment by Darkmift** [comment]
closed
