### ISSUE TITLE
SVG component implementation

### ISSUE THREAD

**Issue by rotembarsela** [Maakaf/maakaf-website#27]
### The problem
using SVGs inside next/image (Image component of Nextjs) is not the best approach,
the problem is that if one want to apply hover: or dark: or fill-red-500 for example using tailwind classNames it wont work

### Solution
Creating a global component that handle SVGs and passing props to the SVG's <b>path > stroke</b> values

### Example

![image](https://github.com/Maakaf/maakaf-website/assets/44998514/1a9f14f1-0ae7-4ec3-96c9-96c2d3ee5c84)

on hover:
![image](https://github.com/Maakaf/maakaf-website/assets/44998514/db9c5c2e-3684-4bce-a38e-64dde2c3e3b0)

* https://react-svgr.com/docs/next/ (an option to acheive that)

### Additional information

if you have alternative solution, please feel free to comment

**Comment by RoyTennenbaum** [comment]
If anyone has an idea and would like to try working on it, comment here and you'll get assigned :)

**Comment by Darkmift** [comment]
I'll do some research for best approach

**Comment by Jenish-Dhanani** [comment]
Hello there,

I recently encountered a similar issue with an SVG icon. I'd like to share an impressive CSS trick that can help you achieve the desired output. This can be accomplished using the CSS filter property, and you can also integrate it using Tailwind CSS if preferred. This technique is particularly useful when you're aiming for a single-color appearance for the SVG.

You can take a look at the example image here:
![image](https://github.com/Maakaf/maakaf-website/assets/99007146/3c9298e7-82e9-4fab-ae4d-810d1001d47f)

Feel free to let me know if these techniques prove useful for your situation. I'd be glad to contribute and assist further.

For additional information, you can refer to the following resources:

[MDN Web Docs - CSS filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter)
[Quackit - CSS hue-rotate function](https://www.quackit.com/css/functions/css_hue-rotate_function.cfm)

**Comment by Darkmift** [comment]
Interesting approach!

In order to maximize compliance with figma design I feel this is the best approximation.

**Comment by rotembarsela** [comment]
> Hello there,
> 
> I recently encountered a similar issue with an SVG icon. I'd like to share an impressive CSS trick that can help you achieve the desired output. This can be accomplished using the CSS filter property, and you can also integrate it using Tailwind CSS if preferred. This technique is particularly useful when you're aiming for a single-color appearance for the SVG.
> 
> You can take a look at the example image here: ![image](https://user-images.githubusercontent.com/99007146/261839856-3c9298e7-82e9-4fab-ae4d-810d1001d47f.png)
> 
> Feel free to let me know if these techniques prove useful for your situation. I'd be glad to contribute and assist further.
> 
> For additional information, you can refer to the following resources:
> 
> [MDN Web Docs - CSS filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter) [Quackit - CSS hue-rotate function](https://www.quackit.com/css/functions/css_hue-rotate_function.cfm)

It seems like it will solve our problem, @Darkmift do you want to PR the solution? The colors for the hover are on the figma, I implemented the classes on globals.css, Idm do it myself if you are busy.

@Jenish-Dhanani Thanks 🙏

**Comment by Jenish-Dhanani** [comment]
@rotembarsela & @Darkmift It's my pleasure! I am happy to help in the future also!

**Comment by Darkmift** [comment]
I am not at liberty rn to examine this properly.

Go ahead and implement it @rotembarsela

**Comment by rotembarsela** [comment]
@RoyTennenbaum I'll implement it tonight

**Comment by rotembarsela** [comment]
done #32

**Comment by RoyTennenbaum** [comment]
It's great to see you guys working together to solve issues, true open-source community spirit!

I was busy these couple of days, will check out the solution this afternoon

**Comment by RoyTennenbaum** [comment]
closing #31 💯
