### ISSUE TITLE
Projects not loading

### ISSUE THREAD

**Issue by Darkmift** [Maakaf/maakaf-website#291]
### Description

A recnet bug when loading the page is in need of fixing.

![image](https://github.com/Maakaf/maakaf-website/assets/12433441/88742feb-f961-4abe-b30b-c934841a3596)
![image](https://github.com/Maakaf/maakaf-website/assets/12433441/d558d681-1964-4280-8691-f376c5987649)

**Comment by supervxn** [comment]
@Tamir198 thanks for taking care of it. Once the pr (#292) is merged please change the label of the issue to "done".
