### ISSUE TITLE
Navbar "Community" Dropdown

### ISSUE THREAD

**Issue by rotembarsela** [Maakaf/maakaf-website#33]
### Description

Description
as I posted on discord, should we use HeadlessUI lib or writing it by ourself?
write down your suggestions

Relevant files:

components/Header/Header.tsx

### Screenshots

![image](https://github.com/Maakaf/maakaf-website/assets/44998514/99e7f184-8b25-48db-8d1f-13b4ce4c28b7)

**Comment by RoyTennenbaum** [comment]
Why not try writing it ourselves first? I would like to assign anyone that would write this with no dependencies.

If none raise their hand we'll add an external library like the one you suggested @rotembarsela
