### ISSUE TITLE
CI/CD Pipeline :toolbox:

### ISSUE THREAD

**Issue by rotembarsela** [Maakaf/maakaf-website#36]
### Description

Creation of CI/CD Pipeline which make a Contributor that push a new PR to do the following conditions so it will get the :white_check_mark: "All checks have passed" 

### Following checks:
* prettier:  format: npx prettier --write .
* linter: format: npx prettier --write .

- create CONTRIBUTING.md file on the root folder of the project, explaning the steps to do before submitting a new PR

**Comment by EmilyMatt** [comment]
I can take care of this one^
