### ISSUE TITLE
title section's SVG - adjust size and responsiveness

### ISSUE THREAD

**Issue by RoyTennenbaum** [Maakaf/maakaf-website#40]
### Description

- [ ] On figma the svg should be 650 width & 800 height on xl display size
- [ ] Adjust svg responsiveness to all screen sizes
- [ ] Make sure the title section is responsive as well

### Screenshots

![image](https://github.com/Maakaf/maakaf-website/assets/121032859/b61abb33-332d-4344-956c-e3474f8b11c3)

### Additional information

[figma link](https://www.figma.com/file/Ib05mHSvinzf9NNqIqftLR/Maakaf?type=design&node-id=1082-2596&mode=design&t=JDqJ20YuMRUpz2AN-0)

**Comment by oshri1997** [comment]
Please assign me to this issue .

**Comment by RoyTennenbaum** [comment]
Good luck!
