### ISSUE TITLE
fully complete "BeOurFriends" section

### ISSUE THREAD

**Issue by RoyTennenbaum** [Maakaf/maakaf-website#42]
### Description

Design (blue dots and lines) is incomplete
create the designs using tailwind css and with no exported images. 

for examples of the tailwind-created design see Paths.tsx component created by @itaim18 :)

### Additional information

[figma link](https://www.figma.com/file/Ib05mHSvinzf9NNqIqftLR/Maakaf?type=design&node-id=1082-2475&mode=design&t=vgLHgBDYB4WgsOG5-0)

**Comment by Etinger-Asaf** [comment]
Hi, please assign me to this issue.

**Comment by Drorka** [comment]
i started experimenting with designing this component to better fit the figma. would like to be assigned and get my code checked

**Comment by RoyTennenbaum** [comment]
I was not available for the past 2 days, @Etinger-Asaf sorry for not noticing your request, there will be more issues to come.
@Drorka you did great on this one
