### ISSUE TITLE
Fix Paths.tsx component

### ISSUE THREAD

**Issue by RoyTennenbaum** [Maakaf/maakaf-website#43]
### Description

The columns are not vertically aligned on several viewport sizes (you'll see it when playing with the responsivity in dev tools, screenshots attached).
The middle button might wrap and cause the button to span over two lines - undesired behavior.

Only for the brave hearted and/or CSS enthusiasts ;)

### Screenshots

![image](https://github.com/Maakaf/maakaf-website/assets/121032859/3a51b97f-2ba9-428c-87c7-c630395631dc)
![image](https://github.com/Maakaf/maakaf-website/assets/121032859/dd733696-269f-4faf-9491-edbedd1c8143)

### Additional information

[figma link](https://www.figma.com/file/Ib05mHSvinzf9NNqIqftLR/Maakaf?type=design&node-id=1082-2475&mode=design&t=vgLHgBDYB4WgsOG5-0)

**Comment by or-schneider** [comment]
@RoyTennenbaum  Assign me :)

**Comment by RoyTennenbaum** [comment]
Enjoy :)
