### ISSUE TITLE
About page - title section

### ISSUE THREAD

**Issue by RoyTennenbaum** [Maakaf/maakaf-website#45]
### Description

create the title section and only the space for the carrousel,
carrousel will be made on a separate issue.

! create a component called AboutTitle.tsx and link it to the page.tsx located in 'About' folder

### Additional information

Notice spacing, margins, paddings, colors etc.
[all here](https://www.figma.com/file/Ib05mHSvinzf9NNqIqftLR/Maakaf?type=design&node-id=51-508&mode=design&t=vgLHgBDYB4WgsOG5-0)

**Comment by SuperDuperAlon** [comment]
On it

**Comment by SuperDuperAlon** [comment]
Done, I would love some feedback if possible
