### ISSUE TITLE
Carrousel - design & functionality

### ISSUE THREAD

**Issue by RoyTennenbaum** [Maakaf/maakaf-website#46]
### Description

create a page called carrousel.tsx in About folder and link it to page.tsx in the same folder.

Please, do not download any dependency unless it is truly necessary!

### Screenshots

![image](https://github.com/Maakaf/maakaf-website/assets/121032859/1ba749d9-1ece-4001-9c3c-49e8e1680cd8)

### Additional information

[figma](https://www.figma.com/file/Ib05mHSvinzf9NNqIqftLR/Maakaf?type=design&node-id=51-508&mode=design&t=vgLHgBDYB4WgsOG5-0)

**Comment by adirkandel** [comment]
Let me do this one

**Comment by RoyTennenbaum** [comment]
Beware @adirkandel, I have high expectations from you 😉
