### ISSUE TITLE
Sidebar component

### ISSUE THREAD

**Issue by RoyTennenbaum** [Maakaf/maakaf-website#48]
### Description

create a page called Sidebar.tsx in 'components/Header' folder.

### Additional information

Notice spacing, margins, paddings, colors etc.
[all here](https://www.figma.com/file/Ib05mHSvinzf9NNqIqftLR/Maakaf?type=design&node-id=51-508&mode=design&t=vgLHgBDYB4WgsOG5-0)

**Comment by rotembarsela** [comment]
I'll do that

**Comment by RoyTennenbaum** [comment]
Great! and please do it with no external dependencies :)

**Comment by rotembarsela** [comment]
#54
