### ISSUE TITLE
Add header

### ISSUE THREAD

**Issue by RoyTennenbaum** [Maakaf/maakaf-website#5]
### Description

Create the "Header" component.
Include in it the community logo & Dark mode icon, just like the figma design (copy from there).

Relevant files:
- components/Header/Header.tsx

### Additional information

- Make sure to render the nav bar invisible (we are planing to use the home page as a landing page for the time being, so an invisible nav bar is fine for now).
- Please be accurate to the figma design.

**Comment by rotembarsela** [comment]
May I work on that?

**Comment by itaim18** [comment]
I'd love to be paired with whomever will work on it

**Comment by RoyTennenbaum** [comment]
I somehow missed these comments, apologies.
replied to you @rotembarsela on your recent PR.
