### ISSUE TITLE
Add the title section - top of the home page

### ISSUE THREAD

**Issue by RoyTennenbaum** [Maakaf/maakaf-website#6]
### Description

The title section contains the title, paragraph, discord button, and the blue-green-red lines design.
Please make sure to be accurate to the figma design in sizes, colors, etc. It's all there!

Relevant files:
- components/Home/titleSection.tsx
- components/Home/titleDesign.tsx
- app/page.tsx

**Comment by rotembarsela** [comment]
I did it on the last PR (navbar and darkmode)
