### ISSUE TITLE
footer not attached to the bottom

### ISSUE THREAD

**Issue by RoyTennenbaum** [Maakaf/maakaf-website#63]
### Description

when on a page that has less content than the viewport, the footer is attached to the bottom of the content and not the bottom of the page.

### Screenshots

![image](https://github.com/Maakaf/maakaf-website/assets/121032859/5579f21b-0925-4f79-9340-2fdb49bfc3f5)

**Comment by RuthwikReddy09** [comment]
Give the page a min-height of 100vh and it should work.

**Comment by adirkandel** [comment]
> Give the page a min-height of 100vh and it should work.

@RuthwikReddy09 I recommend to check how it works on mobile. [read this](https://stackoverflow.com/questions/74144034/why-is-the-css-height100vh-rule-exceeding-the-viewport-height-on-mobile-device) also inside this post you will find answers like [this one](https://stackoverflow.com/a/76673307/3677229)

**Comment by RoyTennenbaum** [comment]
@develad Thank you' #69 closes #63
