### ISSUE TITLE
i18n - create a JSON file for all hebrew content

### ISSUE THREAD

**Issue by RoyTennenbaum** [Maakaf/maakaf-website#67]
### Description

what the title says xD

Basically turn all the text in the website into json variables.

**Comment by itaim18** [comment]
Looks like a fine issue, could it be worked along with creating a localization button and its logic?

**Comment by RoyTennenbaum** [comment]
> Looks like a fine issue, could it be worked along with creating a localization button and its logic?
@itaim18 After speaking with Uriel it seems we currently don't need translation, but having all the text in a seperate file could make our code more readable

And after speaking with @noams24 I am relinquishing this issue :)

**Comment by adirkandel** [comment]
@RoyTennenbaum so we can close this one?

**Comment by Darkmift** [comment]
@noams24 can you link the PR here?
Whats the status?

I am closing this lets resume in #138

**Comment by noams24** [comment]
> @noams24 can you link the PR here? Whats the status?
> 
> I am closing this lets resume in #138

@Darkmift 
Link to PR: https://github.com/Maakaf/maakaf-website/pull/95/files
I only made an example of using a json file for hebrew content, I didn't applied it the whole project.
Maybe using MD files will be a better option.

**Comment by Darkmift** [comment]
> > @noams24 can you link the PR here? Whats the status?
> > I am closing this lets resume in #138
> 
> @Darkmift Link to PR: https://github.com/Maakaf/maakaf-website/pull/95/files I only made an example of using a json file for hebrew content, I didn't applied it the whole project. Maybe using MD files will be a better option.

Hi @noams24 good stuff!
please see here:
https://github.com/Maakaf/maakaf-website/issues/138#issuecomment-1983092757
