### ISSUE TITLE
Add quote section

### ISSUE THREAD

**Issue by RoyTennenbaum** [Maakaf/maakaf-website#7]
### Description

Section that contains the quote: "קוד פתוח הוא בסיס לקהילה שעובדת יחד..."
This section makes for a good first issue, make sure to create it exactly like the figma design.

Relevant files:
- components/Home/Quote.tsx
- app/page.tsx

**Comment by Etinger-Asaf** [comment]
Hi, please assign me to this issue :)

**Comment by RoyTennenbaum** [comment]
Have fun :)

**Comment by RoyTennenbaum** [comment]
How is it going? ask in our community discord channel if you encounter any issues or need to clarify something 😃

**Comment by RoyTennenbaum** [comment]
Is all well? @Etinger-Asaf

**Comment by Etinger-Asaf** [comment]
Yes, thanks for asking.
I had some minor delays.
I'm sure I'll submit the PR this weekend. 💪🏻

**Comment by RoyTennenbaum** [comment]
#49
