### ISSUE TITLE
Create the project card

### ISSUE THREAD

**Issue by RoyTennenbaum** [Maakaf/maakaf-website#74]
### Description

relevant files:

components/Projects/ProjectCard/ProjectCard.tsx
app/projects/page.tsx

### Screenshots

![image](https://github.com/Maakaf/maakaf-website/assets/121032859/e7b2902e-e3a7-431b-ba80-898c738bed87)

### Additional information

Further notes on [figma](https://www.figma.com/file/Ib05mHSvinzf9NNqIqftLR/Maakaf?type=design&node-id=51-508&mode=design&t=GyAJ58EvT8NxYioy-0)

**Comment by or-schneider** [comment]
Assign me :)

**Comment by RoyTennenbaum** [comment]
Have fun!
