### ISSUE TITLE
Broken Navigation links

### ISSUE THREAD

**Issue by itaim18** [Maakaf/maakaf-website#78]
### Description

In Next.js' App router the folders build the routes in the app.
But in order for this to work the links need to consider whether the folders are case sensitive.
which the routing system is not considering right now.
Needs to be fixed at `@/components/Footer/Footer.tsx`, `@/components/Header/Header.tsx`, `@/components/Header/NavDropdown.tsx`, `@/components/Header/Sidebar.tsx`, `@/components/MemberPics/MemberPics.tsx`

**Comment by RoyTennenbaum** [comment]
@nitzanto

**Comment by nitzanto** [comment]
> @nitzanto please reply here so I may assign you

Done

**Comment by Darkmift** [comment]
fixed by #144
