### ISSUE TITLE
Add "BeOurFriends" section

### ISSUE THREAD

**Issue by RoyTennenbaum** [Maakaf/maakaf-website#8]
### Description

The section that starts with "מה תקבלו מלהיות חברים בקהילה שלנו", under the quote section.
make sure to follow the figma design.

Relevant files:
- components/Home/BeOurFriends.tsx
- app/page.tsx

### Additional information

If/when creating sub components is necessary, create a new folder called "BeOurFriends" and insert the BeOurFriends.tsx in there, together with all related sub components.

**Comment by hilell-elsh** [comment]
I will take this

**Comment by RoyTennenbaum** [comment]
you're assigned, good luck @hilell-elsh !
