### ISSUE TITLE
Home page - Accessibility and SEO 📝

### ISSUE THREAD

**Issue by rotembarsela** [Maakaf/maakaf-website#83]
### Description

Refactor the home page so it will be close to 100% on all the checkmarks in the Lighthouse Extension.

files including:
- app/layout.tsx (Header/Footer)
- app/page.tsx (Components):
      TitleSection
      Quote
      BeOurFriends
      Paths
      MembersPics
      WhatNow

- Example:
## Fix the code according to the test output (Desktop and Mobile)
![image](https://github.com/Maakaf/maakaf-website/assets/44998514/4d040171-7fe6-49c5-aead-90bf59ecc649)

### Additional information

Lighthouse Extension: https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk

**Comment by RoyTennenbaum** [comment]
Great suggestion, any who want to attempt this reply to this comment to get yourself assigned :)

**Comment by itaim18** [comment]
I'll try my best :)

**Comment by itaim18** [comment]
I am workin on the a11y rn, and saw the perfomance downsided, unforutnatley it couldn't be because of my changes but probably a PR with some unused JS but also could be resulted by bad data throlling.
![WhatsApp Image 2023-09-07 at 03 36 30](https://github.com/Maakaf/maakaf-website/assets/37772742/55f6687f-db54-4171-86b6-624cf2214369)

**Comment by rotembarsela** [comment]
> I am workin on the a11y rn, and saw the perfomance downsided, unforutnatley it couldn't be because of my changes but probably a PR with some unused JS but also could be resulted by bad data throlling. ![WhatsApp Image 2023-09-07 at 03 36 30](https://user-images.githubusercontent.com/37772742/266170970-55f6687f-db54-4171-86b6-624cf2214369.jpeg)

Might be because of the background image on home page header, someone is working on that rn, try to check that again when he is finish

**Comment by RoyTennenbaum** [comment]
@itaim18 are you on the latest fork? just noticed this issue has 'SEO' in its title and @Drorka already handled some of it.
Just making sure there are no collisions

**Comment by Drorka** [comment]
> @itaim18 are you on the latest fork? just noticed this issue has 'SEO' in its title and @Drorka already handled some of it. Just making sure there are no collisions

@RoyTennenbaum It doesn't seem like it's going to conflict with my latest merged pr. I briefly checked the lighthouse score and the issues presented there are mainly about loading time related to the background element.
