### ISSUE TITLE
Background over flow of skeleton_loader.png/skeleton_loader_dark.png

### ISSUE THREAD

**Issue by develad** [Maakaf/maakaf-website#84]
### Description

Background over flow of skeleton_loader.png/skeleton_loader_dark.png with screen size width over 1280px

![maakaf-website vercel app_](https://github.com/Maakaf/maakaf-website/assets/70572668/1f6b30fa-7308-419d-8e95-04d05315f671)

**Comment by RoyTennenbaum** [comment]
@nitzanto reply here as well so I may assign you

**Comment by nitzanto** [comment]
> @nitzanto reply here as well so I may assign you

Done

**Comment by Darkmift** [comment]
Upon inspection this issue is no longer occuring.
