### ISSUE TITLE
Add Metadata to app routes (SEO)

### ISSUE THREAD

**Issue by Drorka** [Maakaf/maakaf-website#85]
### Description

- Create a metadata interface
- Use metadata in all app routes (Homepage, projects page, paths pages etc.)

Metadata should include:
- Title
- Description
- OpenGraph(?)

### Additional information

Next.js metadata documentation
https://nextjs.org/docs/app/building-your-application/optimizing/metadata

**Comment by Drorka** [comment]
please assign me to this issue (:

**Comment by itaim18** [comment]
@RoyTennenbaum change the label to `enhancement`
