### ISSUE TITLE
Add "Paths" section (המסלולים שלנו)

### ISSUE THREAD

**Issue by RoyTennenbaum** [Maakaf/maakaf-website#9]
### Description

make sure to follow the figma design.

Relevant files:
- components/Home/Paths.tsx
- app/page.tsx

### Additional information

If/when creating sub components is necessary, create a new folder called "Paths" and insert the Paths.tsx in there, together with all related sub components.

**Comment by itaim18** [comment]
This looks great, I'd love to be assigned

**Comment by RoyTennenbaum** [comment]
Good luck Itai :)

**Comment by itaim18** [comment]
#16 solves this issue
