### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by noams24** [Maakaf/maakaf-website#94]
### Description

Where is the dark mode button?

### Screenshots

![image](https://github.com/Maakaf/maakaf-website/assets/80849999/14135fa7-c58c-44e9-b469-6454f788f9a0)

**Comment by Drorka** [comment]
Currently I can see the button.
What is your screen size? Maybe it has something to do with that?

**Comment by noams24** [comment]
Maybe it's my browser.. I'm using Brave.

**Comment by adirkandel** [comment]
@noams24 can you take care of it?

**Comment by noams24** [comment]
I can try

**Comment by noams24** [comment]
@adirkandel  @RoyTennenbaum The default theme should be light or dark?

**Comment by noams24** [comment]
I fixed it in the PR @adirkandel

**Comment by adirkandel** [comment]
@noams24 you resolved it on #95 right?

**Comment by noams24** [comment]
Yes
