### ISSUE TITLE
Maintainers - Steps strip

### ISSUE THREAD

**Issue by adirkandel** [Maakaf/maakaf-website#97]
### Description

Build the steps strip as described in [Figma](https://www.figma.com/file/Ib05mHSvinzf9NNqIqftLR/Maakaf?type=design&node-id=2406%3A4945&mode=design&t=h2PHWSvkSaHG0pEE-1)

### Screenshots

<img width="1003" alt="image" src="https://github.com/Maakaf/maakaf-website/assets/12512909/6838074e-4ac3-4266-a40a-91ed62888218">

### Additional information

Insert the component into `app/maintainers/page.tsx`

**Comment by adirkandel** [comment]
@develad would you like me to assign this issue to you?

**Comment by develad** [comment]
@adirkandel 
#96

**Comment by develad** [comment]
@adirkandel 
#96 
Done!

**Comment by adirkandel** [comment]
Resolved in #96
