### ISSUE TITLE
Maintainers - QnA accordion

### ISSUE THREAD

**Issue by adirkandel** [Maakaf/maakaf-website#98]
### Description

Build the **QnA accordion** as described in [Figma](https://www.figma.com/file/Ib05mHSvinzf9NNqIqftLR/Maakaf?type=design&node-id=2406%3A4945&mode=design&t=h2PHWSvkSaHG0pEE-1)

### Screenshots

<img width="1003" alt="image" src="https://github.com/Maakaf/maakaf-website/assets/12512909/d56e8671-6f02-498a-90d8-b245edf14253">

### Additional information

Insert the component into app/maintainers/page.tsx

**Comment by adirkandel** [comment]
@develad do you want this issue?

**Comment by develad** [comment]
#93 
I **Don't** going to change the implementation to this issue so no

**Comment by adirkandel** [comment]
Done in #113
